// GENERATED by scripts/generate-icon-glyphs.mjs from Phosphor Icons (MIT,
// https://phosphoricons.com). Do not edit — regenerate.

/**
 * THE ICON SET — one family, one grid, three sizes.
 *
 * Every glyph is Phosphor, drawn by one hand on one 256 grid. The names are
 * the product's own and never change, so a call site says what the icon MEANS
 * (IconMatch) and scripts/generate-icon-glyphs.mjs decides what it LOOKS like.
 * One module per icon: a route downloads only the icons it draws.
 *
 * Sizes: 16 inline with text, 20 in menus/buttons/rows, 24 in headers and
 * tiles. Weights: "regular" at rest, "fill" for the selected item, "duotone"
 * for feature tiles and empty states, "bold" only where a glyph sits on a
 * coloured fill under 16px. Every icon inherits `currentColor` and is
 * decorative (aria-hidden) unless given `alt`.
 */
export type { IconProps, IconWeight } from "./glyph";
export { IconHome } from "./glyphs/IconHome";
export { IconTrophy } from "./glyphs/IconTrophy";
export { IconUsers } from "./glyphs/IconUsers";
export { IconRupee } from "./glyphs/IconRupee";
export { IconHelp } from "./glyphs/IconHelp";
export { IconSearch } from "./glyphs/IconSearch";
export { IconBell } from "./glyphs/IconBell";
export { IconMenu } from "./glyphs/IconMenu";
export { IconClose } from "./glyphs/IconClose";
export { IconChevronDown } from "./glyphs/IconChevronDown";
export { IconChevronRight } from "./glyphs/IconChevronRight";
export { IconChevronLeft } from "./glyphs/IconChevronLeft";
export { IconArrowLeft } from "./glyphs/IconArrowLeft";
export { IconArrowRight } from "./glyphs/IconArrowRight";
export { IconArrowUp } from "./glyphs/IconArrowUp";
export { IconExternal } from "./glyphs/IconExternal";
export { IconList } from "./glyphs/IconList";
export { IconGrid } from "./glyphs/IconGrid";
export { IconKebab } from "./glyphs/IconKebab";
export { IconAlert } from "./glyphs/IconAlert";
export { IconInfo } from "./glyphs/IconInfo";
export { IconCheck } from "./glyphs/IconCheck";
export { IconCircle } from "./glyphs/IconCircle";
export { IconCheckCircle } from "./glyphs/IconCheckCircle";
export { IconClock } from "./glyphs/IconClock";
export { IconEye } from "./glyphs/IconEye";
export { IconStar } from "./glyphs/IconStar";
export { IconStarOutline } from "./glyphs/IconStarOutline";
export { IconSpark } from "./glyphs/IconSpark";
export { IconCalendar } from "./glyphs/IconCalendar";
export { IconMatch } from "./glyphs/IconMatch";
export { IconPin } from "./glyphs/IconPin";
export { IconGavel } from "./glyphs/IconGavel";
export { IconShieldCheck } from "./glyphs/IconShieldCheck";
export { IconLedger } from "./glyphs/IconLedger";
export { IconReceipt } from "./glyphs/IconReceipt";
export { IconFileCheck } from "./glyphs/IconFileCheck";
export { IconLock } from "./glyphs/IconLock";
export { IconBolt } from "./glyphs/IconBolt";
export { IconRefresh } from "./glyphs/IconRefresh";
export { IconLayers } from "./glyphs/IconLayers";
export { IconBroadcast } from "./glyphs/IconBroadcast";
export { IconTv } from "./glyphs/IconTv";
export { IconPhone } from "./glyphs/IconPhone";
export { IconMail } from "./glyphs/IconMail";
export { IconCamera } from "./glyphs/IconCamera";
export { IconMessageCircle } from "./glyphs/IconMessageCircle";
export { IconGlobe } from "./glyphs/IconGlobe";
export { IconPlay } from "./glyphs/IconPlay";
export { IconSun } from "./glyphs/IconSun";
export { IconMoon } from "./glyphs/IconMoon";
export { IconVolume } from "./glyphs/IconVolume";
export { IconVolumeOff } from "./glyphs/IconVolumeOff";
export { IconLogOut } from "./glyphs/IconLogOut";
export { IconUser } from "./glyphs/IconUser";
export { IconChart } from "./glyphs/IconChart";
export { IconMegaphone } from "./glyphs/IconMegaphone";
export { IconSend } from "./glyphs/IconSend";
export { IconWallet } from "./glyphs/IconWallet";
export { IconCrown } from "./glyphs/IconCrown";
export { IconFlag } from "./glyphs/IconFlag";
export { IconCog } from "./glyphs/IconCog";
export { IconPlus } from "./glyphs/IconPlus";
export { IconPencil } from "./glyphs/IconPencil";
export { IconCopy } from "./glyphs/IconCopy";
export { IconUpload } from "./glyphs/IconUpload";
export { IconDownload } from "./glyphs/IconDownload";
export { IconImage } from "./glyphs/IconImage";
export { IconFilter } from "./glyphs/IconFilter";
export { IconBat } from "./glyphs/IconBat";
export { IconBall } from "./glyphs/IconBall";
export { IconFile } from "./glyphs/IconFile";
export { IconEyeOff } from "./glyphs/IconEyeOff";
export { IconXCircle } from "./glyphs/IconXCircle";
export { IconMinusCircle } from "./glyphs/IconMinusCircle";
export { IconKey } from "./glyphs/IconKey";
export { IconDevice } from "./glyphs/IconDevice";
export { IconTrash } from "./glyphs/IconTrash";
export { IconInbox } from "./glyphs/IconInbox";
export { IconPause } from "./glyphs/IconPause";
export { IconSkipBack } from "./glyphs/IconSkipBack";
export { IconSkipForward } from "./glyphs/IconSkipForward";
