// GENERATED by scripts/generate-icon-glyphs.mjs from Phosphor Icons (MIT,
// https://phosphoricons.com). Do not edit — regenerate.
import { glyph } from "../glyph";

export const IconArrowUp = glyph("IconArrowUp", {
  regular: (
    <path d="M205.66,117.66a8,8,0,0,1-11.32,0L136,59.31V216a8,8,0,0,1-16,0V59.31L61.66,117.66a8,8,0,0,1-11.32-11.32l72-72a8,8,0,0,1,11.32,0l72,72A8,8,0,0,1,205.66,117.66Z" />
  ),
  fill: (
    <path d="M207.39,115.06A8,8,0,0,1,200,120H136v96a8,8,0,0,1-16,0V120H56a8,8,0,0,1-5.66-13.66l72-72a8,8,0,0,1,11.32,0l72,72A8,8,0,0,1,207.39,115.06Z" />
  ),
  duotone: (
    <>
      <path d="M200,112H56l72-72Z" opacity="0.2" />
      <path d="M205.66,106.34l-72-72a8,8,0,0,0-11.32,0l-72,72A8,8,0,0,0,56,120h64v96a8,8,0,0,0,16,0V120h64a8,8,0,0,0,5.66-13.66ZM75.31,104,128,51.31,180.69,104Z" />
    </>
  ),
});
