// GENERATED by scripts/generate-icon-glyphs.mjs from Phosphor Icons (MIT,
// https://phosphoricons.com). Do not edit — regenerate.
import { glyph } from "../glyph";

export const IconArrowLeft = glyph("IconArrowLeft", {
  regular: (
    <path d="M224,128a8,8,0,0,1-8,8H59.31l58.35,58.34a8,8,0,0,1-11.32,11.32l-72-72a8,8,0,0,1,0-11.32l72-72a8,8,0,0,1,11.32,11.32L59.31,120H216A8,8,0,0,1,224,128Z" />
  ),
  fill: (
    <path d="M224,128a8,8,0,0,1-8,8H120v64a8,8,0,0,1-13.66,5.66l-72-72a8,8,0,0,1,0-11.32l72-72A8,8,0,0,1,120,56v64h96A8,8,0,0,1,224,128Z" />
  ),
  duotone: (
    <>
      <path d="M112,56V200L40,128Z" opacity="0.2" />
      <path d="M216,120H120V56a8,8,0,0,0-13.66-5.66l-72,72a8,8,0,0,0,0,11.32l72,72A8,8,0,0,0,120,200V136h96a8,8,0,0,0,0-16ZM104,180.69,51.31,128,104,75.31Z" />
    </>
  ),
});
