// One-command local bootstrap (LOCAL_SETUP.md): prerequisites → infrastructure
// → environment → migrations → RLS roles → demo seed → validation. Idempotent:
// safe to re-run any time; never overwrites an existing .env.local.
import { execSync, spawnSync } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const run = (cmd, opts = {}) => execSync(cmd, { cwd: root, stdio: "inherit", ...opts });
const capture = (cmd) => {
  const result = spawnSync(cmd, { cwd: root, shell: true, encoding: "utf8" });
  return { code: result.status ?? 1, out: `${result.stdout ?? ""}${result.stderr ?? ""}` };
};
const fail = (message, hint) => {
  console.error(`\n✗ ${message}`);
  if (hint) console.error(`  → ${hint}`);
  process.exit(1);
};
const step = (name) => console.log(`\n── ${name} ${"─".repeat(Math.max(1, 60 - name.length))}`);

// 1 · Prerequisites -----------------------------------------------------------
step("1/7 prerequisites");
if (capture("docker info --format ok").code !== 0)
  fail("Docker is not running", "Start Docker Desktop (or the docker daemon) and re-run.");
const nodeMajor = Number(process.versions.node.split(".")[0]);
if (nodeMajor < 24)
  fail(
    `Node ${process.versions.node} found, >=24 required`,
    "Install Node 24+ (see .node-version).",
  );
if (capture("pnpm --version").code !== 0)
  fail("pnpm not found", "corepack enable && corepack prepare pnpm@latest --activate");
console.log("✓ docker, node, pnpm");

// 2 · Environment file --------------------------------------------------------
step("2/7 environment (.env.local)");
const envPath = join(root, ".env.local");
if (existsSync(envPath)) {
  console.log("✓ .env.local exists — left untouched");
} else {
  writeFileSync(
    envPath,
    `# Generated by pnpm setup:local — local development only; never put a real
# secret here. Every variable is validated fail-closed by each app's env.ts.

# Local docker-compose Postgres (non-secret by design)
DATABASE_URL=postgres://desiauction:desiauction@localhost:5433/desiauction
LOG_LEVEL=info
PORT=4000
APP_VERSION=dev
# Web ⇄ engine shared secret; the e2e suite expects this dev default.
ENGINE_SECRET=dev-engine-secret

# --- production-posture mode (optional; see docs/operations/LOCAL_TESTING.md) —
# run the web tier under the non-BYPASSRLS app role exactly like production:
# DATABASE_URL=postgres://desiauction_app:local-app@localhost:5433/desiauction
# SYSTEM_DATABASE_URL=postgres://desiauction_system:local-system@localhost:5433/desiauction
`,
  );
  console.log("✓ .env.local generated with local defaults");
}

// 3 · Infrastructure ----------------------------------------------------------
step("3/7 infrastructure (docker compose)");
const compose = capture("docker compose up -d");
if (compose.code !== 0) {
  // The most common non-obvious failure is a corrupted Docker Desktop VM store
  // (read-only overlayfs / containerd I/O error) — no CLI command heals it.
  const corruptStore = /read-only file system|input\/output error|meta\.db|failed to mount/i.test(
    compose.out,
  );
  fail(
    "docker compose up failed",
    corruptStore
      ? "Docker Desktop's VM storage is corrupted (read-only FS / I/O error). " +
          "Restart Docker Desktop — or Docker Desktop → Troubleshoot → Clean / Purge data " +
          "(or reboot) — then re-run `pnpm setup:local`. See docs/operations/LOCAL_SETUP.md.\n  " +
          compose.out.trim().split("\n").slice(-2).join("\n  ")
      : compose.out.trim().slice(-500),
  );
}
process.stdout.write("waiting for postgres ");
let dbUp = false;
for (let i = 0; i < 60; i++) {
  if (capture("docker exec desiauction-next-db-1 pg_isready -U desiauction").code === 0) {
    dbUp = true;
    break;
  }
  process.stdout.write(".");
  execSync("sleep 1");
}
if (!dbUp) fail("postgres did not become healthy", "docker compose logs db");
const minio = capture("curl -sf http://localhost:9000/minio/health/live");
console.log(
  `\n✓ postgres healthy · minio ${minio.code === 0 ? "healthy" : "starting (non-blocking)"}`,
);

// 4 · Dependencies ------------------------------------------------------------
step("4/7 dependencies");
if (!existsSync(join(root, "node_modules"))) run("pnpm install --frozen-lockfile");
console.log("✓ node_modules present");

// 5 · Database: migrations + RLS roles ---------------------------------------
step("5/7 migrations + RLS roles");
run("pnpm --filter @desiauction/db db:migrate");
run("pnpm --filter @desiauction/engine db:migrate");
const roles = capture(
  "docker exec -i desiauction-next-db-1 psql -U desiauction -d desiauction " +
    "-v app_password='local-app' -v system_password='local-system' " +
    "-v engine_password='local-engine' -v runner_password='local-runner' " +
    "< ops/db/create-app-role.sql",
);
if (roles.code !== 0) fail("role bootstrap failed", roles.out.slice(-400));
console.log("✓ migrations applied · four-role recipe in place (app/system/engine/runner)");

// 6 · Demo data ---------------------------------------------------------------
step("6/7 demo data (repeatable)");
run("pnpm --filter @desiauction/web seed:demo");

// 7 · Validation --------------------------------------------------------------
step("7/7 validation");
run("pnpm env:check");
run("node scripts/health.mjs --no-apps");
console.log(`
SETUP COMPLETE — start everything with:  pnpm dev
  web     http://localhost:3000        engine  http://localhost:4000
  minio   http://localhost:9001 (console, desiauction/desiauction)
  OTP inbox (dev codes)  http://localhost:3000/dev/inbox
Demo credentials are printed above (seed step) and on every pnpm dev.`);
