// Token pipeline per doc 18: DTCG JSON -> CSS custom properties per theme +
// a typed TS module. Generated files are committed; CI rebuilds and fails on
// drift. (Tailwind preset from doc 18 deferred until a Tailwind consumer
// exists — recorded deviation, IP-1_DESIGN §5.)
import StyleDictionary from "style-dictionary";

const KEBAB = (path) => path.join("-").replace(/-default$/, "");

StyleDictionary.registerTransform({
  name: "name/da-kebab",
  type: "name",
  transform: (token) => KEBAB(token.path),
});

StyleDictionary.registerFormat({
  name: "typescript/da-tokens",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((t) => `  "${t.name}": "var(--${t.name})",`)
      .join("\n");
    return [
      "// GENERATED by style-dictionary — do not edit (pnpm --filter @desiauction/ui build)",
      "export const tokens = {",
      entries,
      "} as const;",
      "",
      "export type SemanticToken = keyof typeof tokens;",
      "export const semanticTokenNames = Object.keys(tokens) as SemanticToken[];",
      "",
    ].join("\n");
  },
});

const semanticOnly = (token) => token.filePath.includes("themes/");
const primitiveNonColor = (token) => !token.filePath.includes("themes/") && token.$type !== "color";

function themePlatform(theme) {
  return {
    transforms: ["name/da-kebab"],
    buildPath: "src/generated/",
    files: [
      {
        destination: `${theme}.css`,
        format: "css/variables",
        filter: semanticOnly,
        options: { selector: `[data-theme="${theme}"]`, outputReferences: false },
      },
    ],
  };
}

const builds = [
  {
    source: ["tokens/primitives.json"],
    platforms: {
      primitives: {
        transforms: ["name/da-kebab"],
        buildPath: "src/generated/",
        files: [
          {
            destination: "primitives.css",
            format: "css/variables",
            filter: primitiveNonColor,
            options: { selector: ":root" },
          },
        ],
      },
    },
  },
  {
    source: ["tokens/primitives.json", "tokens/themes/floodlight.json"],
    platforms: {
      floodlight: themePlatform("floodlight"),
      ts: {
        transforms: ["name/da-kebab"],
        buildPath: "src/generated/",
        files: [{ destination: "tokens.ts", format: "typescript/da-tokens", filter: semanticOnly }],
      },
    },
  },
  {
    source: ["tokens/primitives.json", "tokens/themes/daylight.json"],
    platforms: { daylight: themePlatform("daylight") },
  },
];

for (const config of builds) {
  const sd = new StyleDictionary({ ...config, log: { verbosity: "silent" } });
  await sd.buildAllPlatforms();
}
console.log("tokens built: primitives.css, floodlight.css, daylight.css, tokens.ts");
